name: motion
description: A fancy Widget that applies a gyroscope-based motion effect to its child.
version: 1.0.1
homepage: https://cendre.me
repository: https://github.com/mrcendre/motion
issue_tracker: https://github.com/mrcendre/motion/issues?q=is%3Aissue+is%3Aopen


environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
